# fly.toml app configuration file generated for gucci9-bot on 2026-02-10T09:58:50+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gucci9-bot'
primary_region = 'sin'

[build]

[deploy]
  strategy = 'immediate'

[env]
  PYTHONUNBUFFERED = '1'

[processes]
  app = 'python bot.py'

[[mounts]]
  source = 'gucci9_bot_data'
  destination = '/data'

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
